### ISSUE TITLE
Sentence Parser Error

### ISSUE THREAD

**Issue by cmorbaab** [HazyResearch/snorkel#336]
I get this error when I try to define a Sentence Parser Object.

```
Traceback (most recent call last):
  File "/Users/cameronbaab/Documents/Marker-Reader4/{DELETE} TESTER.py", line 63, in <module>
    print biomarkerGenerator(parseDocIntoWords())
  File "/Users/cameronbaab/Documents/Marker-Reader4/{DELETE} TESTER.py", line 28, in parseDocIntoWords
    sentence_parser = SentenceParser()
  File "/Users/cameronbaab/Documents/Marker-Reader4/snorkel/snorkel/parser.py", line 138, in __init__
    loc = os.path.join(os.environ['SNORKELHOME'], 'parser')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'SNORKELHOME'
```

**Comment by ajratner** [comment]
The `SNORKELHOME` environment variable needs to be set- this will be done automatically if you run with `./run.sh`.  Updating README now, sorry you beat me to this!
