### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by subarnas** [HazyResearch/snorkel#551]
I get the following error message when I try the tutorial, any advice to get past this would be appreciated:
Clearing existing...
Running UDF...
[=                                       ] 0%-- listing properties --
port=12345
timeout=600000
Starting server on port 12345 with timeout of 600000 milliseconds.
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at sun.net.httpserver.ServerImpl.<init>(ServerImpl.java:100)
        at sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java:50)
        at sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35)
        at com.sun.net.httpserver.HttpServer.create(HttpServer.java:130)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.run(StanfordCoreNLPServer.java:692)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.main(StanfordCoreNLPServer.java:756)
[========================================] 100%Traceback (most recent call last):
  File "CDR_Tutorial_2_new.py", line 23, in <module>
    corpus_parser.apply(list(doc_preprocessor))
  File "/DATA/subarna/snorkel/snorkel2/snorkel-master/snorkel/udf.py", line 40, in apply
    self.apply_st(xs, progress_bar, clear=clear, count=count, **kwargs)
  File "/DATA/subarna/snorkel/snorkel2/snorkel-master/snorkel/udf.py", line 72, in apply_st
    udf.session.commit()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 874, in commit
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 461, in commit
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 441, in _prepare_impl
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 2139, in flush
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 2259, in _flush
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/langhelpers.py", line 60, in __exit__
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 2223, in _flush
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/unitofwork.py", line 384, in execute
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/unitofwork.py", line 642, in execute_aggregate
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/persistence.py", line 181, in save_obj
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 945, in execute
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1189, in _execute_context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 203, in raise_from_cause
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1182, in _execute_context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 470, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table context has no column named stable_id [SQL: u'INSERT INTO context (type, stable_id) VALUES (?, ?)'] [parameters: ('document', '227508::document:0:0')]

**Comment by stephenbach** [comment]
Hi,

This looks like a migration issue to v0.5. Can you delete snorkel.db in the intro tutorial directory and see if rerunning works?

**Comment by subarnas** [comment]
Thanks, that worked.

**Comment by stephenbach** [comment]
Great! Thanks!
