### ISSUE TITLE
TF "segment ids are not increasing by 1" error

### ISSUE THREAD

**Issue by bhancock8** [HazyResearch/snorkel#554]
Running the SparseLogisticRegression model, I get an error from tensorflow about segment ideas not increasing by 1. Any idea what's up with that?

Input:
disc_model.train(F_unlabeled, train_marginals, n_epochs=20, lr=0.001)

Output:
[SparseLR] lr=0.001 l1=0.0 l2=0.0
[SparseLR] Building model
[SparseLR] Training model  #epochs=20  batch=100
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-21-505e45b541cc> in <module>()
----> 1 disc_model.train(F_unlabeled, train_marginals, n_epochs=20, lr=0.001)

/Users/bradenhancock/snorkel/snorkel/learning/logistic_regression.pyc in train(self, X, training_marginals, n_epochs, lr, batch_size, l1_penalty, l2_penalty, print_freq, rebalance)
    104             for i in range(0, n, batch_size):
    105                 r = min(n-1, i+batch_size)
--> 106                 loss, _, nnz = self._run_batch(X_train, y_train, i, r)
    107                 epoch_loss += loss
    108             # Print training stats

/Users/bradenhancock/snorkel/snorkel/learning/logistic_regression.pyc in _run_batch(self, X_train, y_train, i, r)
    202             self.ids:     ids,
    203             self.weights: weights,
--> 204             self.Y:       y_batch,
    205         })
    206 

/Users/bradenhancock/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    764     try:
    765       result = self._run(None, fetches, feed_dict, options_ptr,
--> 766                          run_metadata_ptr)
    767       if run_metadata:
    768         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/Users/bradenhancock/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
    962     if final_fetches or final_targets:
    963       results = self._do_run(handle, final_targets, final_fetches,
--> 964                              feed_dict_string, options, run_metadata)
    965     else:
    966       results = []

/Users/bradenhancock/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1012     if handle is None:
   1013       return self._do_call(_run_fn, self._session, feed_dict, fetch_list,
-> 1014                            target_list, options, run_metadata)
   1015     else:
   1016       return self._do_call(_prun_fn, self._session, handle, feed_dict,

/Users/bradenhancock/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
   1032         except KeyError:
   1033           pass
-> 1034       raise type(e)(node_def, op, message)
   1035 
   1036   def _extend_graph(self):

InvalidArgumentError: segment ids are not increasing by 1
	 [[Node: embedding_lookup_sparse_3 = SegmentSum[T=DT_FLOAT, Tindices=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_lookup_sparse_3/mul, embedding_lookup_sparse_3/Cast)]]

Caused by op u'embedding_lookup_sparse_3', defined at:
  File "/Users/bradenhancock/anaconda/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/bradenhancock/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/bradenhancock/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/Users/bradenhancock/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 653, in launch_instance
    app.start()
  File "/Users/bradenhancock/anaconda/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 389, in start
    ioloop.IOLoop.instance().start()
  File "/Users/bradenhancock/anaconda/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/Users/bradenhancock/anaconda/lib/python2.7/site-packages/tornado/ioloop.py", line 866, in start
    handler_func(fd_obj, events)
  File "/Users/bradenhancock/anaconda/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/bradenhancock/anaconda/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/Users/bradenhancock/anaconda/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/bradenhancock/anaconda/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/Users/bradenhancock/anaconda/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/bradenhancock/anaconda/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 252, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/bradenhancock/anaconda/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 213, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/bradenhancock/anaconda/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 362, in execute_request
    user_expressions, allow_stdin)
  File "/Users/bradenhancock/anaconda/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 175, in do_execute
    shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/bradenhancock/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/bradenhancock/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2827, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/bradenhancock/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-21-505e45b541cc>", line 1, in <module>
    disc_model.train(F_unlabeled, train_marginals, n_epochs=20, lr=0.001)
  File "/Users/bradenhancock/snorkel/snorkel/learning/logistic_regression.py", line 88, in train
    self._build()
  File "/Users/bradenhancock/snorkel/snorkel/learning/logistic_regression.py", line 153, in _build
    params=w, sp_ids=sparse_ids, sp_weights=sparse_vals, combiner='sum'
  File "/Users/bradenhancock/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/embedding_ops.py", line 333, in embedding_lookup_sparse
    embeddings = math_ops.segment_sum(embeddings, segment_ids, name=name)
  File "/Users/bradenhancock/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2307, in segment_sum
    segment_ids=segment_ids, name=name)
  File "/Users/bradenhancock/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/Users/bradenhancock/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/bradenhancock/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): segment ids are not increasing by 1
	 [[Node: embedding_lookup_sparse_3 = SegmentSum[T=DT_FLOAT, Tindices=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_lookup_sparse_3/mul, embedding_lookup_sparse_3/Cast)]]

**Comment by henryre** [comment]
Well this is what happens when you have to use a function called `embedding_lookup_sparse` to do spmv. Looking into it.

**Comment by henryre** [comment]
@bhancock8 can you check to see if your sparse feature matrix has any rows that are all zeros. If so: as a test, can you add the [sparse identity matrix](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.sparse.identity.html) to the feature matrix and try running logistic regression again?

**Comment by bhancock8** [comment]
@henryre yes, there was at least one row that had all zeros. I added a padded identity matrix (since there were more rows than columns, I had the diagonal loop around for another go through the columns) and the error goes away.

**Comment by henryre** [comment]
@bhancock8 ok just pushed a patch to the `spmv-fix` branch. Can you try it out?

**Comment by bhancock8** [comment]
Fixed! You da best.
