### ISSUE TITLE
spaCy not installed error when trying to run from snorkel.parser import TSVDocPreprocessor

### ISSUE THREAD

**Issue by suvinks** [HazyResearch/snorkel#752]
Hi

>>> from snorkel.parser import TSVDocPreprocessor

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "snorkel/parser/__init__.py", line 5, in <module>
    from .spacy_parser import *
  File "snorkel/parser/spacy_parser.py", line 11, in <module>
    raise Exception("spaCy not installed. Use `pip install spacy`.")
Exception: spaCy not installed. Use `pip install spacy`.

The problem is I do have spacy installed. I am using ubuntu and followed all the steps related to snorkel installation. 
Am getting this error when I am trying to run the Intro tutorial

**Comment by ajratner** [comment]
Hi @suvinks ,

Try running the second line [here](https://spacy.io/docs/usage/) and let me know if that helps?

**Comment by suvinks** [comment]
Thanks for the response 
I tried running the below command. it returned error

**snorkel$ python -m spacy download en**

Traceback (most recent call last):
  File "/home/XXXX/anaconda2/envs/py2Env/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/home/XXXX/anaconda2/envs/py2Env/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/home/XXXX/anaconda2/envs/py2Env/lib/python2.7/site-packages/spacy/__init__.py", line 5, in <module>
    from .deprecated import resolve_model_name
  File "/home/XXXX/anaconda2/envs/py2Env/lib/python2.7/site-packages/spacy/deprecated.py", line 8, in <module>
    from .cli import download
  File "/home/XXXX/anaconda2/envs/py2Env/lib/python2.7/site-packages/spacy/cli/__init__.py", line 5, in <module>
    from .train import train, train_config
  File "/home/XXXX/anaconda2/envs/py2Env/lib/python2.7/site-packages/spacy/cli/train.py", line 8, in <module>
    from ..scorer import Scorer
  File "/home/XXXX/anaconda2/envs/py2Env/lib/python2.7/site-packages/spacy/scorer.py", line 4, in <module>
    from .gold import tags_to_entities
  File "spacy/morphology.pxd", line 25, in init spacy.gold (spacy/gold.cpp:23505)
  File "spacy/vocab.pxd", line 27, in init spacy.morphology (spacy/morphology.cpp:10713)
ImportError: /home/XXX/anaconda2/envs/py2Env/lib/python2.7/site-packages/spacy/vocab.so: undefined symbol: _ZTINSt8ios_base7failureB5cxx11E

**Comment by jason-fries** [comment]
Hi @suvinks,
It look like you are using anaconda to manage your packages (or at least that's the kernel Jupyter is using). Did you make certain you were in the anaconda environment before installing spaCy
i.e., running  `source activate <ENV_NAME>` before `pip install -U spacy`?

**Comment by suvinks** [comment]
Yes I did that. It still didn't work. 

However I tried 
conda install spacy -c conda-forge and then the model got downloaded correctly :)

Am not sure what is happening with the pip installation. It would be good for others if you mention this on the snorkel installation Read me. 

Thank you for the help. Cheers

**Comment by bhancock8** [comment]
Just to leave a paper trail here, I ran into the same issue as well recently when setting up a new machine, and the solution for me came from uninstalling both my pip and conda installed versions of spacy and then reinstalling with just pip.
