### ISSUE TITLE
Error importing from tensorflow

### ISSUE THREAD

**Issue by subarnas** [HazyResearch/snorkel#765]
Traceback (most recent call last):
  File "cgr.py", line 11, in <module>
    from snorkel.lf_helpers import (
  File "/DATA/subarna/snorkel/snorkel-0.6.2/snorkel/lf_helpers.py", line 5, in <module>
    from .learning.utils import MentionScorer
  File "/DATA/subarna/snorkel/snorkel-0.6.2/snorkel/learning/__init__.py", line 5, in <module>
    from .disc_models.rnn import reRNN, TagRNN, TextRNN
  File "/DATA/subarna/snorkel/snorkel-0.6.2/snorkel/learning/disc_models/rnn/__init__.py", line 1, in <module>
    from re_rnn import reRNN
  File "/DATA/subarna/snorkel/snorkel-0.6.2/snorkel/learning/disc_models/rnn/re_rnn.py", line 3, in <module>
    from rnn_base import RNNBase
  File "/DATA/subarna/snorkel/snorkel-0.6.2/snorkel/learning/disc_models/rnn/rnn_base.py", line 17, in <module>
    class RNNBase(TFNoiseAwareModel):
  File "/DATA/subarna/snorkel/snorkel-0.6.2/snorkel/learning/disc_models/rnn/rnn_base.py", line 51, in RNNBase
    cell_type=tf.contrib.rnn.BasicLSTMCell, word_dict=SymbolTable(),
AttributeError: 'module' object has no attribute 'BasicLSTMCell'

I have tensorflow-0.12 installed, specifically tensorflow-0.12.1-cp27-none-linux_x86_64.whl. 
Am I missing something else?

**Comment by jason-fries** [comment]
Hi @subarnas,
You'll need tensorflow>=1.0 installed to use Snorkel. You should be able to just upgrade easily via `pip` or any other package manager.

**Comment by subarnas** [comment]
Thanks, that worked.  It has been a while since I tried this tutorial when the older version of tensorflow worked :-).
