### ISSUE TITLE
Duplicate key issue at candidate extraction stage

### ISSUE THREAD

**Issue by subarnas** [HazyResearch/snorkel#785]
Ran into this issue at the candidate extraction step. 

Traceback (most recent call last):
  File "cgr.py", line 81, in <module>
    candidate_extractor.apply(sents, split=k)
  File "/DATA/subarna/snorkel/snorkel-0.6.2/snorkel/candidates.py", line 189, in apply
    super(PretaggedCandidateExtractor, self).apply(xs, split=split, **kwargs)
  File "/DATA/subarna/snorkel/snorkel-0.6.2/snorkel/udf.py", line 43, in apply
    self.apply_st(xs, progress_bar, clear=clear, count=count, **kwargs)
  File "/DATA/subarna/snorkel/snorkel-0.6.2/snorkel/udf.py", line 66, in apply_st
    for y in udf.apply(x, **kwargs):
  File "/DATA/subarna/snorkel/snorkel-0.6.2/snorkel/candidates.py", line 243, in apply
    tc.load_id_or_insert(self.session)
  File "/DATA/subarna/snorkel/snorkel-0.6.2/snorkel/models/context.py", line 151, in load_id_or_insert
    {'type': self._get_table_name(), 'stable_id': stable_id}).inserted_primary_key[0]
  File "/DATA/subarna/anaconda2/envs/py2Env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1107, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/DATA/subarna/anaconda2/envs/py2Env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/DATA/subarna/anaconda2/envs/py2Env/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/DATA/subarna/anaconda2/envs/py2Env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/DATA/subarna/anaconda2/envs/py2Env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/DATA/subarna/anaconda2/envs/py2Env/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/DATA/subarna/anaconda2/envs/py2Env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/DATA/subarna/anaconda2/envs/py2Env/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "context_pkey"
DETAIL:  Key (id)=(3104) already exists.
 [SQL: 'INSERT INTO context (type, stable_id) VALUES (%(type)s, %(stable_id)s) RETURNING context.id'] [parameters: {'stable_id': u'16419169::span:916:918', 'type': 'span'}]

**Comment by subarnas** [comment]
Was able to fix it.
