### ISSUE TITLE
Parsing bugs with `pdftotree` HTML

### ISSUE THREAD

**Issue by lukehsiao** [HazyResearch/snorkel#836]
**This only occurs for `pdftotree` output with the old parser.**

When running the fonduer [maximum storage temperature tutorial](https://github.com/HazyResearch/snorkel/blob/8465d489060673fe9941a800844ca3a67860ccdd/snorkel/contrib/fonduer/tutorials/hardware/max_storage_temp_tutorial.ipynb) on commit 8465d48 of the fonduer branch.

We run into this error

```
OperationalError: (psycopg2.OperationalError) index row size 3072 exceeds maximum 2712 for index "part_attr_feature_keys_pkey"
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
 [SQL: 'ALTER TABLE part_attr_feature_keys ADD PRIMARY KEY(key)']
```
when using the attached files as the HTML data.

[OperationalError.zip](https://github.com/HazyResearch/snorkel/files/1503017/OperationalError.zip)

That is, if you unzip the above HTML files and store them in `tutorials/hardware/data` and update the notebook to:

```python
docs_path = os.environ['FONDUERHOME'] + '/tutorials/hardware/data/[unzipped name]/'
```

you'll see the error.

It's most likely caused by the non-standard use of tags that are produced by TreeStructure, where lots of information is contained within the tags, unlike a typical HTML document.

**Comment by lukehsiao** [comment]
Using the new parser on the `fonduer_parser` branch, I'm hitting [this breakpoint in `parser.py:409-412`](https://github.com/HazyResearch/snorkel/blob/a6122b4ae64df507df8a0bd215903decafb94dd2/snorkel/contrib/fonduer/fonduer/parser.py#L409-L412) with the error:

```

**Comment by lukehsiao** [comment]
Running the [`test_parser.py`](https://github.com/HazyResearch/snorkel/blob/660bdf21256ac621b6a300cc8825610f52e78574/tutorials/fonduer/hardware/test_parser.py) script results in the following output:

```
[/127.0.0.1:40700] API call w/annotators tokenize,ssplit,pos,depparse,lemma,ner
[ERROR]list index out of range
> /home/lwhsiao/repos/snorkel-hazy/snorkel/contrib/fonduer/fonduer/parser.py(368)parse_structure()
-> for parts in self.lingual_parse(document,self.contents[parsed:batch_end]):
(Pdb) 
Process OmniParserUDF-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/lwhsiao/repos/snorkel-hazy/snorkel/udf.py", line 156, in run
    for y in self.apply(x, **self.apply_kwargs):
  File "/home/lwhsiao/repos/snorkel-hazy/snorkel/contrib/fonduer/fonduer/parser.py", line 174, in apply
    for phrase in self.parse_structure(document, text):
  File "/home/lwhsiao/repos/snorkel-hazy/snorkel/contrib/fonduer/fonduer/parser.py", line 368, in parse_structure
    for parts in self.lingual_parse(document,self.contents[parsed:batch_end]):
  File "/home/lwhsiao/repos/snorkel-hazy/snorkel/contrib/fonduer/fonduer/parser.py", line 368, in parse_structure
    for parts in self.lingual_parse(document,self.contents[parsed:batch_end]):
  File "/usr/lib/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python2.7/bdb.py", line 68, in dispatch_line
    if self.quitting: raise BdbQuit
BdbQuit
[/127.0.0.1:40704] API call w/annotators tokenize,ssplit,pos,depparse,lemma,ner
no match found
no match found
[/127.0.0.1:40706] API call w/annotators tokenize,ssplit,pos,depparse,lemma,ner
no match found
no match found
[/127.0.0.1:40704] API call w/annotators tokenize,ssplit,pos,depparse,lemma,ner
[/127.0.0.1:40706] API call w/annotators tokenize,ssplit,pos,depparse,lemma,ner
[/127.0.0.1:40704] API call w/annotators tokenize,ssplit,pos,depparse,lemma,ner
no match found
no match found
no match found
no match found
no match found
no match found
[/127.0.0.1:40706] API call w/annotators tokenize,ssplit,pos,depparse,lemma,ner
Documents: 4
Phrases: 5978
Paragraphs: 3727
Figures: 47
```

**Comment by lukehsiao** [comment]
Using `spacy` as our NLP parser instead of `CoreNLP`, results in the following output for `test_parser.py`.

```
...
no match found
no match found
no match found
no match found
no match found
Documents: 6
Phrases: 4996
Paragraphs: 5278
Figures: 62
```

**Comment by lukehsiao** [comment]
This issue is a bit irrelevant now. We will need to work on refactoring the new parser to work with pdftotree, which will take place in the [fonduer repo](https://github.com/hazyresearch/fonduer). Closing this issue.
