### ISSUE TITLE
KeyError: 'SNORKELHOME'

### ISSUE THREAD

**Issue by zkawan** [HazyResearch/snorkel#893]
The following error occurs when I do, "from snorkel.annotations import load_gold_labels". I have set the environment variable running  

Traceback (most recent call last):
  File "training-snorkel.py", line 23, in <module>
    from snorkel.annotations import load_gold_labels
  File "../PycharmProjects/snorkel-master/snorkel/annotations.py", line 13, in <module>
    from .features import get_span_feats
  File "../PycharmProjects/snorkel-master/snorkel/features/__init__.py", line 10, in <module>
    from .entity_features import *
  File "../PycharmProjects/snorkel-master/snorkel/features/entity_features.py", line 8, in <module>
    sys.path.append(os.environ['SNORKELHOME'] + '/treedlib/treedlib')
  File "../new/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'SNORKELHOME'

**Comment by DingPengfei** [comment]
same error

**Comment by HarrietLyBui** [comment]
Anyone has figured out how to solve this issue?
