### ISSUE TITLE
Libraries are not compatible with python 3

### ISSUE THREAD

**Issue by HarrietLyBui** [HazyResearch/snorkel#945]
When I try to run 
```

from lib.init import *
from lib.util import check_exercise_1, check_exercise_2
```
I got error:

```
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Traceback (most recent call last):

  File "/home/ec2-user/anaconda3/envs/py3Env/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-3-9d715e95bc1a>", line 5, in <module>
    from lib.util import check_exercise_1, check_exercise_2

  File "/home/ec2-user/snorkel/tutorials/workshop/lib/__init__.py", line 2, in <module>
    from .util import *

  File "/home/ec2-user/snorkel/tutorials/workshop/lib/util.py", line 84
    print 'Correct!' if v else 'Sorry, try again!'
                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Correct!' if v else 'Sorry, try again!')?
```
I am using Python3.6

**Comment by stephenbach** [comment]
Thanks for checking out Snorkel! Just FYI, this issue is specific to the workshop tutorial. Snorkel itself, including the intro tutorial, works with Python 2 and 3.

Leaving this issue open as a TODO to update the workshop materials.

**Comment by jason-fries** [comment]
@HarrietLyBui  See the new workshop updates -- this fixes the Python 2/3 issues!

**Comment by ronyarmon** [comment]
I just tried with the current version on the repo (Python 3.6.8,Anaconda, MacOs 10.13.3) and getting the same error message

**Comment by garaud** [comment]
Hi,

From the intro tutorial, first notebook. When you import `TSVDocPreprocessor`

```python
from snorkel.parser import TSVDocPreprocessor
```

I've got this error:

```

~/snorkel/parser/__init__.py in <module>
      1 from __future__ import absolute_import
      2 
----> 3 from snorkel.parser.corenlp import *
      4 from snorkel.parser.corpus_parser import *
      5 from snorkel.parser.doc_preprocessors import *

~/snorkel/parser/corenlp.py in <module>
      5 from __future__ import unicode_literals
      6 from builtins import *
----> 7 from future.utils import iteritems
      8 
      9 import os

ModuleNotFoundError: No module named 'future'
```

This line `from future.utils import iteritems` does not work in Python 3
