### ISSUE TITLE
LabelAnnotator doesn't recognize labeling function schema?

### ISSUE THREAD

**Issue by debnil** [HazyResearch/snorkel#990]
```Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/debnil/projects/recon/labeling/run_generative_labeling.py", line 27, in <module>
    run_labeling(session, args.feature)
  File "/home/debnil/projects/recon/labeling/run_generative_labeling.py", line 18, in run_labeling
    L_train = labeler.apply(split=0, parallelism=1)
  File "/home/debnil/projects/snorkel/snorkel/annotations.py", line 197, in apply
    count=cids_count, **kwargs)
  File "/home/debnil/projects/snorkel/snorkel/udf.py", line 48, in apply
    self.apply_st(xs, progress_bar, clear=clear, count=count, **kwargs)
  File "/home/debnil/projects/snorkel/snorkel/udf.py", line 71, in apply_st
    for y in udf.apply(x, **kwargs):
  File "/home/debnil/projects/snorkel/snorkel/annotations.py", line 267, in apply
    c = self.session.query(Candidate).filter(Candidate.id == cid).one()
  File "/home/debnil/projects/recon/.env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2894, in one
    ret = self.one_or_none()
  File "/home/debnil/projects/recon/.env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2864, in one_or_none
    ret = list(self)
  File "/home/debnil/projects/recon/.env/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 98, in instances
    util.raise_from_cause(err)
  File "/home/debnil/projects/recon/.env/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/debnil/projects/recon/.env/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 79, in instances
    rows = [proc(row) for row in fetch]
  File "/home/debnil/projects/recon/.env/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 741, in polymorphic_instance
    _instance = polymorphic_instances[discriminator]
  File "/home/debnil/projects/recon/.env/local/lib/python2.7/site-packages/sqlalchemy/util/_collections.py", line 729, in __missing__
    self[key] = val = self.creator(key)
  File "/home/debnil/projects/recon/.env/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 725, in configure_subclass_mapper
    discriminator)
AssertionError: No such polymorphic_identity u'gang' is defined```
```
Getting from following code -- 
```
def run_labeling(session, feature):
    lfs_arr = lfs.get_lfs_by_feature(feature)
    lfs_arr = [lf[1] for lf in lfs_arr] 
    # Above makes list of labeling function pointers
    labeler = LabelAnnotator(lfs=lfs_arr)
    L_train = labeler.apply(split=0, parallelism=1)
    L_dev = labeler.apply(split=1, parallelism=1)
```

Pretty simple call to LabelAnnotator following tutorial, but I don't understand the schema issue here and am not sure what I'm doing wrong. Thanks!

**Comment by phosseini** [comment]
@debnil I have the same problem, could you resolve your issue?
